### PR TITLE
Cleaned up the README file, added `startshapedefinitions` command

### PR DESCRIPTION
**Pull request by palewire**
Changes:
- Small clean up on the README file as I worked my way through a Hello World on this end
- A new custom management command,  startshapedefinitions, that will mint a definitions.py file in the SHAPEFILES_DIR

### CODE REVIEW

**Comment by onyxfish** [comment]
Hey, nice! I'm happy to merge this. Would you mind adding a note about how to use the new management command to the README?

**Comment by palewire** [comment]
Glad to help.. I think that's in the README. 

Here's something really pedantic, you've got a command called "load_shapefiles," but don't Django custom managements commands typically omit underscores from their names and just smush it all together (think "syncdb," "loaddata," and "startproject").

**Comment by onyxfish** [comment]
I dig it. I'll merge this in today. Good call on moving the ider and namer functions into the core code.

Regarding pedantry and naming, I'm normally all for it, but I think this project has been around long enough that I don't just want to switch it. I've seen plenty of other django apps that don't adhere to the very non-pythonic smushed naming convention.

**Comment by palewire** [comment]
Bump bump bumpity bump

**Comment by onyxfish** [comment]
Thanks for the nudge, I'd forgotten all about this!

**Comment by palewire** [comment]
No problem. Might see some more annoying stuff from me on this one. Tho I'm not totally clear to get gunning the project using it just yet.

**Comment by onyxfish** [comment]
Happy to see more.  You may notice I decided to take your advice re: naming consistency as well.

**Pull request merged**
