### PR TITLE
multi db support

### PR DESCRIPTION
**Pull request by shaneshifflett**
Updated mgmt commands to support multiple databases.  Because it uses the django.db.connections, a dbrouter doesn't work

### CODE REVIEW

**Comment by nosamanuel** [comment]
Any objection to using --database as the flag here for the sake of being consistent with the core Django commands?

**Comment by shaneshifflett** [comment]
None whatsoever!  Thanks.

**Comment by onyxfish** [comment]
Merged, thanks! I did use --database as the flag for consistency sake.

**Comment by jpmckinney** [comment]
Just thought I'd mention that this only changes the DB used to look up the `spatial_ref_sys` table - it doesn't change the DB that boundary sets and boundaries are saved to...

**Pull request merged**
